//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_module
    {
        public string codeModule { get; set; }
        public string nomModule { get; set; }
        public Nullable<long> typeModule { get; set; }
        public string description { get; set; }
        public Nullable<long> estActif { get; set; }
    }
}
