//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personnel
    {
        public long persId { get; set; }
        public string sdeId { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string sexe { get; set; }
        public string nomUtilisateur { get; set; }
        public string motDePasse { get; set; }
        public string email { get; set; }
        public string deptId { get; set; }
        public string comId { get; set; }
        public string vqseId { get; set; }
        public string zone { get; set; }
        public string codeDistrict { get; set; }
        public Nullable<long> estActif { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public string dateDebutCollecte { get; set; }
        public string dateFinCollecte { get; set; }
    }
}
