//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_batiment
    {
        public long batimentId { get; set; }
        public string deptId { get; set; }
        public string comId { get; set; }
        public string vqseId { get; set; }
        public string sdeId { get; set; }
        public Nullable<long> zone { get; set; }
        public string disctrictId { get; set; }
        public string qhabitation { get; set; }
        public string qlocalite { get; set; }
        public string qadresse { get; set; }
        public string qrec { get; set; }
        public string qepc { get; set; }
        public Nullable<long> qb1Etat { get; set; }
        public Nullable<long> qb2Type { get; set; }
        public Nullable<long> qb3StatutOccupation { get; set; }
        public Nullable<long> qb4NbreLogeIndividuel { get; set; }
        public Nullable<long> statut { get; set; }
        public string dateEnvoi { get; set; }
        public Nullable<long> isValidated { get; set; }
        public Nullable<long> isSynchroToAppSup { get; set; }
        public Nullable<long> isSynchroToCentrale { get; set; }
        public string dateDebutCollecte { get; set; }
        public string dateFinCollecte { get; set; }
        public Nullable<long> dureeSaisie { get; set; }
        public Nullable<long> isFieldAllFilled { get; set; }
        public Nullable<long> isContreEnqueteMade { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string codeAgentRecenceur { get; set; }
        public Nullable<long> isVerified { get; set; }
    }
}
