//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Materiel
    {
        public long MaterielId { get; set; }
        public string Imei { get; set; }
        public string Serial { get; set; }
        public string Model { get; set; }
        public string Version { get; set; }
        public Nullable<long> AgentId { get; set; }
        public string DateAssignation { get; set; }
        public Nullable<long> IsConfigured { get; set; }
        public string LastSynchronisation { get; set; }
    }
}
