//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_question
    {
        public string codeQuestion { get; set; }
        public string libelle { get; set; }
        public string detailsQuestion { get; set; }
        public string IndicationsQuestion { get; set; }
        public string codeCategorie { get; set; }
        public string nomChamps { get; set; }
        public Nullable<long> typeQuestion { get; set; }
        public Nullable<long> caratereAccepte { get; set; }
        public Nullable<long> nbreValeurMinimal { get; set; }
        public Nullable<long> nbreCaratereMaximal { get; set; }
        public string contrainteSautChampsValeur { get; set; }
        public Nullable<long> estSautReponse { get; set; }
        public string qPrecedent { get; set; }
        public string qSuivant { get; set; }
    }
}
