//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_question_reponse
    {
        public string codeQuestion { get; set; }
        public string codeUniqueReponse { get; set; }
        public string codeReponse { get; set; }
        public string libelleReponse { get; set; }
        public Nullable<long> estEnfant { get; set; }
        public Nullable<long> avoirEnfant { get; set; }
        public string codeParent { get; set; }
        public string qPrecedent { get; set; }
        public string qSuivant { get; set; }
    }
}
