//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ht.ihsi.rgph.epc.database.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logement
    {
        public long logeId { get; set; }
        public Nullable<long> batimentId { get; set; }
        public string sdeId { get; set; }
        public Nullable<long> qlCategLogement { get; set; }
        public Nullable<long> qlin1NumeroOrdre { get; set; }
        public Nullable<long> qlin2StatutOccupation { get; set; }
        public Nullable<long> qlin3TypeLogement { get; set; }
        public Nullable<long> qlin4IsHaveIndividuDepense { get; set; }
        public Nullable<long> qlin5NbreTotalMenage { get; set; }
        public Nullable<long> statut { get; set; }
        public Nullable<long> isValidated { get; set; }
        public Nullable<long> isFieldAllFilled { get; set; }
        public string dateDebutCollecte { get; set; }
        public string dateFinCollecte { get; set; }
        public Nullable<long> dureeSaisie { get; set; }
        public Nullable<long> isContreEnqueteMade { get; set; }
        public Nullable<long> nbrTentative { get; set; }
        public string codeAgentRecenceur { get; set; }
        public Nullable<long> isVerified { get; set; }
    }
}
